import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:campusapp/models/harassment_report.dart';
import 'package:intl/intl.dart';

class PdfService {
  static Future<void> generateAndPrintReport(HarassmentReport report) async {
    final pdf = pw.Document();

    final dateStr = DateFormat('dd MMM yyyy').format(report.incidentDate);
    final createdStr = DateFormat('dd MMM yyyy, HH:mm').format(report.createdAt);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('INCIDENT REPORT', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text('Ref: #${report.id.substring(0, 8).toUpperCase()}', style: pw.TextStyle(color: PdfColors.grey)),
                ],
              ),
              pw.Divider(thickness: 2),
              pw.SizedBox(height: 20),

              // Status Section
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                decoration: pw.BoxDecoration(
                  color: _getStatusColor(report.status),
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
                ),
                child: pw.Text(
                  'STATUS: ${report.status.toUpperCase()}',
                  style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold),
                ),
              ),
              pw.SizedBox(height: 30),

              // Basic Info
              _sectionHeader('Incident Details'),
              _infoRow('Title:', report.title),
              _infoRow('Date:', dateStr),
              _infoRow('Location:', report.location),
              pw.SizedBox(height: 20),

              _sectionHeader('Reporter Information'),
              _infoRow('Name:', report.reporterName ?? 'Not Available'),
              _infoRow('Department:', report.reporterDept ?? 'Not Available'),
              _infoRow('Reported ID:', report.reporterId),
              _infoRow('Filed On:', createdStr),
              pw.SizedBox(height: 20),

              _sectionHeader('Description of Incident'),
              pw.Paragraph(
                text: report.description,
                style: const pw.TextStyle(fontSize: 12),
              ),
              
              pw.Spacer(),
              pw.Divider(),
              pw.Center(
                child: pw.Text('Generated by Campus Care App - Unauthorized sharing prohibited.', 
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
              )
            ],
          );
        },
      ),
    );

    // This opens the native print dialog / save to PDF option
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Incident_Report_${report.id.substring(0,8)}.pdf',
    );
  }

  static pw.Widget _sectionHeader(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Text(title, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
    );
  }

  static pw.Widget _infoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        children: [
          pw.SizedBox(width: 100, child: pw.Text(label, style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
          pw.Expanded(child: pw.Text(value)),
        ],
      ),
    );
  }

  static PdfColor _getStatusColor(String status) {
    switch (status.toLowerCase()) {
      case 'pending': return PdfColors.orange;
      case 'under_review': return PdfColors.blue;
      case 'resolved': return PdfColors.green;
      case 'cancelled': return PdfColors.red;
      default: return PdfColors.grey;
    }
  }
}
